const shimmer = { background: "linear-gradient(90deg,var(--sf-surface-2) 20%,var(--sf-bg) 50%,var(--sf-surface-2) 80%)", backgroundSize: "220% 100%", animation: "analyticsLoading 1.2s infinite", borderRadius: 6 };

export default function AnalyticsLoading() {
  return <main style={{ width: "min(100%,1120px)", margin: "0 auto", padding: "40px 24px 72px" }} role="status" aria-label="Analytics laden"><style>{`@keyframes analyticsLoading{to{background-position:-20% 0}}.analytics-loading-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.analytics-loading-wide{grid-column:1/-1}@media(max-width:900px){.analytics-loading-grid{grid-template-columns:1fr}.analytics-loading-wide{grid-column:auto}}@media(max-width:640px){.analytics-loading-metrics{grid-template-columns:1fr!important}}`}</style><div style={{ ...shimmer, width: 180, height: 30, marginBottom: 10 }} /><div style={{ ...shimmer, width: "min(100%,560px)", height: 14, marginBottom: 24 }} /><div style={{ border: "1px solid var(--sf-border)", borderRadius: 8, padding: 16, marginBottom: 16 }}><div style={{ ...shimmer, width: 230, height: 32, marginBottom: 16 }} /><div style={{ ...shimmer, width: "100%", height: 74 }} /></div><div className="analytics-loading-metrics" style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", border: "1px solid var(--sf-border)", borderRadius: 8, overflow: "hidden", marginBottom: 16 }}>{[0,1,2,3].map((item) => <div key={item} style={{ padding: 16, borderRight: item < 3 ? "1px solid var(--sf-border)" : 0 }}><div style={{ ...shimmer, width: 80, height: 10, marginBottom: 10 }} /><div style={{ ...shimmer, width: 60, height: 24 }} /></div>)}</div><div className="analytics-loading-grid"><LoadingPanel className="analytics-loading-wide" height={210} /><LoadingPanel height={112} /><LoadingPanel height={112} /><LoadingPanel className="analytics-loading-wide" height={112} /><LoadingPanel className="analytics-loading-wide" height={90} /><LoadingPanel className="analytics-loading-wide" height={160} /></div></main>;
}

function LoadingPanel({ height, className = "" }: { height: number; className?: string }) {
  return <div className={className} style={{ border: "1px solid var(--sf-border)", borderRadius: 8, overflow: "hidden" }}><div style={{ height: 60, padding: 16, borderBottom: "1px solid var(--sf-border)", background: "var(--sf-surface-2)" }}><div style={{ ...shimmer, width: 180, height: 14 }} /></div><div style={{ padding: 16 }}><div style={{ ...shimmer, width: "100%", height }} /></div></div>;
}
