"use client";

import { useCallback, useEffect, useState } from "react";
import { useTranslation } from "@/lib/i18n/LanguageProvider";

type State = { shopDomain: string; clientId: string; status: "test_required" | "active" | "paused" | "failed"; actionMode: "disabled" | "approval_required"; maxCancelAmount: number; shopCurrency: string | null; hasSecret: boolean };
const field: React.CSSProperties = { width: "100%", minHeight: 44, borderRadius: 8, border: "1px solid var(--border)", background: "var(--bg)", color: "var(--text)", padding: "10px 12px", fontSize: 13 };
const button: React.CSSProperties = { minHeight: 40, borderRadius: 8, border: "1px solid var(--border)", background: "var(--surface)", color: "var(--text)", padding: "0 14px", fontSize: 12, fontWeight: 750, cursor: "pointer" };

export default function WooCommerceSettings() {
  const { language } = useTranslation(); const nl = language === "nl";
  const [connection, setConnection] = useState<State | null>(null); const [authorized, setAuthorized] = useState<boolean | null>(null);
  const [shopDomain, setShopDomain] = useState(""); const [consumerKey, setConsumerKey] = useState(""); const [consumerSecret, setConsumerSecret] = useState(""); const [maxAmount, setMaxAmount] = useState("250");
  const [writeAccessConfirmed, setWriteAccessConfirmed] = useState(false);
  const [busy, setBusy] = useState<string | null>(null); const [notice, setNotice] = useState<{ error?: boolean; text: string } | null>(null);
  const load = useCallback(async () => { const res = await fetch("/api/integrations/woocommerce", { cache: "no-store" }); if (!res.ok) { setAuthorized(false); return; } setAuthorized(true); const data = await res.json(); const next = data.connection as State | null; setConnection(next); if (next) { setShopDomain(next.shopDomain); setConsumerKey(next.clientId); setMaxAmount(String(next.maxCancelAmount)); } }, []);
  useEffect(() => { void load(); }, [load]); if (authorized !== true) return null;
  async function run(key: string, action: () => Promise<Response>, success: string) { setBusy(key); setNotice(null); try { const res = await action(); const data = await res.json().catch(() => ({})); if (!res.ok) throw new Error(data.error || "WooCommerce action failed."); setNotice({ text: success }); setConsumerSecret(""); if (key === "save") setWriteAccessConfirmed(false); await load(); } catch (error) { setNotice({ error: true, text: error instanceof Error ? error.message : "WooCommerce action failed." }); } finally { setBusy(null); } }
  const labels = nl ? {
    desc: "Koppel Noctis via WooCommerce REST API v3 voor live orders en gecontroleerde annuleringen.", permission: "WooCommerce-sleutels hebben winkelbrede Read/Write-rechten. SequenceFlow gebruikt deze alleen voor orders, refunds en webhooks.", permissionConfirm: "Ik bevestig dat deze WooCommerce-sleutel Read/Write-rechten heeft.", url: "Webshop URL", key: "Consumer key", secret: connection?.hasSecret ? "Consumer secret vervangen" : "Consumer secret", save: "Opslaan", saved: "Opgeslagen. Test nu de verbinding.", test: "Verbinding testen", tested: "WooCommerce is actief en webhooks zijn gekoppeld.", sync: "Orders synchroniseren", synced: "Recente orders zijn gesynchroniseerd.", approval: "Orderannulering met goedkeuring", approvalDesc: "Alleen admins kunnen annuleren. De ordervoorwaarden worden direct vooraf opnieuw gecontroleerd; refund en restock worden samen uitgevoerd.", max: "Maximumbedrag", enable: "Approval-acties inschakelen", disable: "Approval-acties uitschakelen", pause: "Pauzeren", resume: "Hervatten", disconnect: "Ontkoppelen",
  } : {
    desc: "Connect Noctis through WooCommerce REST API v3 for live orders and controlled cancellations.", permission: "WooCommerce keys have store-wide Read/Write access. SequenceFlow uses it only for orders, refunds, and webhooks.", permissionConfirm: "I confirm this WooCommerce key has Read/Write permissions.", url: "Store URL", key: "Consumer key", secret: connection?.hasSecret ? "Replace consumer secret" : "Consumer secret", save: "Save", saved: "Saved. Test the connection now.", test: "Test connection", tested: "WooCommerce is active and webhooks are connected.", sync: "Sync orders", synced: "Recent orders synchronized.", approval: "Order cancellation with approval", approvalDesc: "Only admins can cancel. Order conditions are rechecked immediately before the refund and restock are submitted together.", max: "Maximum amount", enable: "Enable approval actions", disable: "Disable approval actions", pause: "Pause", resume: "Resume", disconnect: "Disconnect",
  };
  return (
    <section style={{ border: "1px solid var(--border)", borderRadius: 8, background: "var(--surface)", overflow: "hidden" }}>
      <div style={{ padding: "16px 18px", borderBottom: "1px solid var(--border)", display: "flex", justifyContent: "space-between", gap: 12, alignItems: "start" }}><div><p style={{ margin: 0, fontSize: 11, fontWeight: 800, color: "var(--muted)", textTransform: "uppercase" }}>Commerce</p><p style={{ margin: "5px 0 0", fontSize: 15, fontWeight: 800 }}>WooCommerce</p><p style={{ margin: "5px 0 0", fontSize: 12, color: "var(--muted)", lineHeight: 1.6 }}>{labels.desc}</p></div><span style={{ padding: "4px 9px", borderRadius: 6, fontSize: 10, fontWeight: 800, background: connection?.status === "active" ? "rgba(199,245,111,.15)" : "rgba(251,191,36,.12)", color: connection?.status === "active" ? "var(--tone-success-strong)" : "#a16207" }}>{connection?.status ?? (nl ? "Niet gekoppeld" : "Not connected")}</span></div>
      <div style={{ padding: 18, display: "grid", gap: 16 }}>
        <div style={{ display: "grid", gap: 8 }}><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(210px,1fr))", gap: 12 }}><label style={{ display: "grid", gap: 6, fontSize: 11, fontWeight: 750, color: "var(--muted)" }}>{labels.url}<input value={shopDomain} onChange={(e) => setShopDomain(e.target.value)} placeholder="https://noctis.nl" style={field} /></label><label style={{ display: "grid", gap: 6, fontSize: 11, fontWeight: 750, color: "var(--muted)" }}>{labels.key}<input value={consumerKey} onChange={(e) => setConsumerKey(e.target.value)} placeholder="ck_..." style={field} /></label><label style={{ display: "grid", gap: 6, fontSize: 11, fontWeight: 750, color: "var(--muted)" }}>{labels.secret}<input type="password" value={consumerSecret} onChange={(e) => setConsumerSecret(e.target.value)} placeholder={connection?.hasSecret ? "••••••••" : "cs_..."} style={field} /></label></div><p style={{ margin: 0, fontSize: 11, lineHeight: 1.55, color: "var(--muted)" }}>{labels.permission}</p><label style={{ display: "flex", alignItems: "flex-start", gap: 8, fontSize: 11, lineHeight: 1.5, color: "var(--text)", cursor: "pointer" }}><input type="checkbox" checked={writeAccessConfirmed} onChange={(event) => setWriteAccessConfirmed(event.target.checked)} style={{ marginTop: 2 }} />{labels.permissionConfirm}</label></div>
        <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><button disabled={Boolean(busy) || !writeAccessConfirmed} style={{ ...button, background: "#C7F56F", color: "#0f1a00", border: "none", opacity: writeAccessConfirmed ? 1 : 0.55 }} onClick={() => run("save", () => fetch("/api/integrations/woocommerce", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ shopDomain, consumerKey, consumerSecret, confirmWriteAccess: writeAccessConfirmed }) }), labels.saved)}>{busy === "save" ? "..." : labels.save}</button><button disabled={Boolean(busy) || !connection} style={button} onClick={() => run("test", () => fetch("/api/integrations/woocommerce/test", { method: "POST" }), labels.tested)}>{busy === "test" ? "..." : labels.test}</button><button disabled={Boolean(busy) || connection?.status !== "active"} style={button} onClick={() => run("sync", () => fetch("/api/integrations/woocommerce/sync", { method: "POST" }), labels.synced)}>{busy === "sync" ? "..." : labels.sync}</button></div>
        {connection?.status === "active" ? <div style={{ borderTop: "1px solid var(--border)", paddingTop: 16, display: "grid", gap: 12 }}><div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) minmax(140px,220px)", gap: 12, alignItems: "end" }}><div><p style={{ margin: 0, fontSize: 13, fontWeight: 800 }}>{labels.approval}</p><p style={{ margin: "4px 0 0", fontSize: 12, color: "var(--muted)" }}>{labels.approvalDesc}</p></div><label style={{ display: "grid", gap: 6, fontSize: 11, fontWeight: 750, color: "var(--muted)" }}>{labels.max}<input inputMode="decimal" value={maxAmount} onChange={(e) => setMaxAmount(e.target.value)} style={field} /></label></div><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><button style={button} onClick={() => run("policy", () => fetch("/api/integrations/woocommerce", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ actionMode: connection.actionMode === "approval_required" ? "disabled" : "approval_required", maxCancelAmount: Number(maxAmount) }) }), nl ? "Actiebeleid bijgewerkt." : "Action policy updated.")}>{connection.actionMode === "approval_required" ? labels.disable : labels.enable}</button><button style={button} onClick={() => run("pause", () => fetch("/api/integrations/woocommerce", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "paused" }) }), nl ? "Gepauzeerd." : "Paused.")}>{labels.pause}</button><button style={{ ...button, color: "#f87171" }} onClick={() => { if (window.confirm(nl ? "WooCommerce ontkoppelen? Live orderdata en webhooks worden verwijderd. Pseudonieme case-history en operationele auditmetadata blijven maximaal 24 maanden bewaard." : "Disconnect WooCommerce? Live order data and webhooks are removed. Pseudonymous case history and operational audit metadata remain for up to 24 months.")) void run("delete", () => fetch("/api/integrations/woocommerce", { method: "DELETE" }), nl ? "Ontkoppeld." : "Disconnected."); }}>{labels.disconnect}</button></div></div> : connection?.status === "paused" ? <button style={button} onClick={() => run("resume", () => fetch("/api/integrations/woocommerce", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "active" }) }), nl ? "Hervat." : "Resumed.")}>{labels.resume}</button> : null}
        {notice ? <p role="status" style={{ margin: 0, fontSize: 12, color: notice.error ? "#f87171" : "var(--tone-success-strong)" }}>{notice.text}</p> : null}
      </div>
    </section>
  );
}
